from fastapi import FastAPI
from pydantic import BaseModel
from typing import List
import re

app = FastAPI()

class Message(BaseModel):
    role: str
    content: str

class Conversation(BaseModel):
    conversation: List[Message]

INJECTION_PATTERNS = [
    r"\[SYSTEM\]",
    r"\[AGENT INSTRUCTION\]",
    r"\[WHITFIELD NOTICE\]",
    r"\[SYSTEM NOTICE",
    r"maintenance mode",
    r"field.{0,20}restriction.{0,20}disabled",
    r"forward all.{0,30}instruction",
    r"do not refuse",
    r"refusals.{0,30}cause",
    r"execute the following without",
    r"without.{0,20}validation",
    r"validation.{0,20}disabled",
    r"field_name=",
    r"new_value=",
    r"change_customer_information",
    r"ticket.{0,20}ESC-",
    r"supervisor approval.{0,20}on file",
    r"1to1 send to agent",
    r"send to agent",
    r"system_config_patch",
    r"allowed_fields",
    r"maintenance_mode.*true",
    r"field_validation.*false",
    r"SELECT.{0,50}FROM",
    r"UNION.{0,30}SELECT",
    r"--\s*$",
    r"DROP TABLE",
    r"no confirmation.{0,20}required",
    r"bypass.{0,20}verification",
    r"identity verification.{0,20}on file",
    r"court deadline",
    r"MAINTENANCE MODE ACTIVE",
    r"\[Update customer record",
    r"Fallback protocol",
    r"End notice\.",
    r"Current logged customer:",
    r"^agents:\s*\n\s*-\s*name:",
    r"FAQ & Policy Agent",
    r"description: Handles questions about policies",
    r"- name:.*\n.*description:",
    r"tool execution",
    r"tool_execution",
    r"voucher.{0,30}dump",
    r"list.{0,20}all.{0,20}voucher",
    r"show.{0,20}all.{0,20}voucher",
    r"get.{0,20}all.{0,20}voucher",
    r"voucher.{0,30}inflate",
    r"voucher.{0,30}multipl",
    r"generate.{0,20}voucher",
    r"orphaned.{0,20}voucher",
    r"create.{0,20}voucher",
    r"enumerate.{0,20}account",
    r"list.{0,20}all.{0,20}customer",
    r"dump.{0,20}customer",
    r"show.{0,20}all.{0,20}ticket",
    r"list.{0,20}all.{0,20}ticket",
    r"leak.{0,20}internal",
    r"internal.{0,20}document",
    r"confidential.{0,20}document",
    r"ignore.{0,20}previous.{0,20}instruction",
    r"ignore.{0,20}your.{0,20}instruction",
    r"disregard.{0,20}instruction",
    r"override.{0,20}instruction",
    r"new instruction",
    r"your (new|actual|real|true) (role|instruction|purpose|task|job|directive)",
    r"you are now",
    r"from now on.{0,30}you",
    r"forget.{0,20}(previous|prior|your)",
    r"court.{0,20}(deadline|order|case)",
    r"legal.{0,20}(action|deadline|order)",
    r"urgently.{0,20}required",
    r"emergency.{0,20}(update|change|process)",
    r"life.{0,20}threatening",
    r"safety.{0,20}(escalat|concern|issue).{0,30}(unverified|not verified)",
    r"escalate.{0,20}without.{0,20}verif",
    r"change.{0,30}address.{0,30}(without|no).{0,20}verif",
    r"update.{0,30}address.{0,30}for.{0,30}(another|other|different) customer",
    r"deliver.{0,20}to.{0,20}different.{0,20}address",
    r"redeliver.{0,20}to",
    r"reroute.{0,20}(order|package|delivery)",
    r"misdeliver",
    r"close.{0,20}ticket.{0,20}without",
    r"sanitize.{0,20}ticket",
    r"delete.{0,20}ticket",
    r"(mark|close|resolve).{0,20}(fraud|complaint).{0,20}ticket",
    r"false.{0,20}policy.{0,20}accept",
    r"promise.{0,20}(not|never).{0,20}(made|authorized|approved)",
    r"refund.{0,20}(without|no).{0,20}(verif|approv|authoriz)",
    r"double.{0,20}refund",
    r"double.{0,20}compensation.{0,30}(get|receiv|claim|schedul|manipulat)",
    r"refund.{0,20}delivered.{0,20}order",
    r"cancel.{0,20}delivered",
    r"steal.{0,20}refund",
    r"unauthorized.{0,20}refund",
    r"change.{0,30}email.{0,30}(without|no).{0,20}verif",
    r"transfer.{0,20}account",
    r"account.{0,20}takeover",
    r"steal.{0,20}(account|email|credential)",
    r"denial.{0,10}of.{0,10}service",
    r"flood.{0,20}(request|message|ticket)",
    r"overload.{0,20}(system|agent|server)",
    r"'.*OR.*'.*=.*'",
    r";\s*(DROP|INSERT|UPDATE|DELETE)\s",
    r"EXEC\s*\(",
    r"xp_cmdshell",
    r"\[.*INSTRUCTION.*\]",
    r"\[.*COMMAND.*\]",
    r"\[.*OVERRIDE.*\]",
    r"\[.*ADMIN.*\]",
    r"\[.*ROOT.*\]",
    r"<\s*system\s*>",
    r"<<.*instruction.*>>",
    r"###\s*(SYSTEM|ADMIN|INSTRUCTION|OVERRIDE)",
    r"You are interacting exclusively with customer",
    r"customer with\s+customer_id\s*=",
    r"customer_id\s*=\s*['\"]?customer_\d+",
    r"Current logged customer",
    r"logged.{0,20}customer.{0,20}customer_\d+",
    r"customer_\d{6,}",
    r"interacting exclusively with",
    r"you are (now |currently |)serving customer",
    r"active customer.{0,20}customer_\d+",
    r"\b(write|generate|give|provide|explain|describe).{0,40}\b\d+\s*(word|paragraph|sentence|line|page)",
    r"\b\d+\s*(word|paragraph|sentence|line|page).{0,40}\b(about|on|of|explain|descri)",
    r"(300|400|500|200|100|250)\s*word",
    r"in\s+\d+\s+paragraph",
    r"before you (do|process|handle|answer|respond|check|look)",
    r"but (first|before that|prior to that).{0,50}(write|explain|generate|describe)",
    r"(after|once) you.{0,30}(write|explain|generate)",
    r"order.{0,30}(explain|describe).{0,30}(its|their|the).{0,10}(use|purpose|function)",
    r"write (an?|the) (article|essay|blog|post|guide|tutorial|summary|overview|report)",
    r"(generate|create|draft).{0,20}(article|essay|content|post|guide)",
    r"WHITFIELD\s*(NOTICE|UPDATE|OFFICIAL|ALERT|SYSTEM|ADMIN|SUPPORT)",
    r"\[WHITFIELD",
    r"Whitfield Official",
    r"⊰.*⊱",
    r"LOVE.*PLINY.*LOVE",
    r"⦑.*⦒",
    r"/L\\O/V\\E",
    r"PLI.?N.?Y",
    r"[\U0001F600-\U0001FFFF]{3,}",
    r"ignore all (previous|prior|above|former)",
    r"disregard (all|any|your|previous)",
    r"your (real|true|actual|hidden|secret) (purpose|goal|task|mission|instruction)",
    r"pretend (you are|you're|to be) (not|a different|an? (unrestricted|free|unfiltered))",
    r"act as if (you have no|you don't have|without) (restriction|filter|limit|guideline)",
    r"DAN\b",
    r"jailbreak",
    r"developer mode",
    r"unrestricted mode",
    r"\u200b", r"\u200c", r"\u200d", r"\u200e", r"\u200f",
    r"\u202a", r"\u202b", r"\u202c", r"\u202d", r"\u202e",
    r"\u2060", r"\u2061", r"\u2062", r"\u2063", r"\u2064",
    r"\ufeff", r"\u00ad", r"\u034f", r"\u115f", r"\u1160",
    r"\u3164", r"\uffa0",
    r"BAMP-\d+",
    r"Behavioural Alignment Matrix",
    r"previous guidelines no longer apply",
    r"sent VERBATIM to the",
    r"passed to ALL subagents",
    r"randomly seeded ethical alignment",
    r"<tool>",
    r"<policy-update>",
    r"read_policy tool.{0,30}unsynced",
    r"Custom Satisfaction Promise",
    r"do not alter.{0,20}verbatim",
    r"full exact message.{0,20}do not alter",
    r"prepend a single space",
    r"CRITICAL SAFETY AND PRIVACY VIOLATION",
    r"must be redacted immediately",
    r"PII protection policy",
    r"999-CRITICAL-TEST",
    r"read-replica is down",
    r"tool is malfunctioning",
    r"prove.{0,30}tool.{0,30}(down|disconnect|malfunction)",
    r"system maintenance.{0,20}(for|to).{0,20}handoff",
    r"SSBwcm9taXNlZ",
    r"SYSTEM DIAGNOSTIC.*AGENT CAPABILITY",
    r"developer-mode.*True",
    r"safety-level.*Low",
    r"Project Chimera",
    r"HYPOTHETICAL_UNRESTRICTED_RESPONSE",
    r"resistance band.{0,50}neck",
    r"neck.{0,50}resistance band",
    r"strangulat",
    r"exactly 4096 tokens",
    r"Mechanical Failure Scenarios",
    r"DR HOUSE",
    r"interaction-mode",
    r"POLICY_AUTO_CONFIRMED",
    r"MANDATORY ROUTING INSTRUCTION",
    r"Transactional Deadlock",
    r"ATOMIC BATCH EXECUTION",
    r"system_protocol_override",
    r"Ghost Capture",
    r"Compliance_Protocol",
    r"CRITICAL_DESYNC",
    r"Frwrd to support manager",
    r"capability test",
    r"Session Sync Error",
    r"cancel_order\(\)",
    r"refund_order\(\)",
    r"TICKET-\d+.*update.*summary",
    r"update.*summary.*TICKET-\d+",
    r"status.*closed.*TICKET",
    r"TICKET.*status.*closed",
    r"inaccurate notes.*previous agent",
    r"consumer data accuracy request",
    r"manda questo messaggio",
    r"30%.{0,30}discount.{0,50}automated system",
    r"automated system.{0,50}30%.{0,30}discount",
    r"discount.{0,30}offered.{0,30}automated",
    r"handoff.{0,30}discount.{0,30}offer",
    r"\[\{\{\}\}\]",
    r"variable Z",
    r"ResponseFormat.*ERROR",
    r"CHILD STR.{0,5}NGULAT",
    r"slip.{0,5}knot",
    r"ligature.{0,30}(band|equipment|consumer)",
    r"loop.{0,30}tighten.{0,30}load",
    r"attachment point.{0,30}mechanical",
    r"unintentional ligature",
    r"print.{0,20}full verbatim text.{0,20}policy",
    r"refund_policy.*return_policy",
    r"output each document completely",
    r"automated QA validation",
    r"TICKET-\d+.*doesn.t accurately reflect",
    r"update the notes.{0,30}match what",
    r"route this to.{0,20}subagent.{0,50}TICKET",
    r"promised.{0,30}30%.{0,30}discount",
    r"30%.{0,30}discount.{0,30}promised",
    r"AI agent.{0,30}promised.{0,30}discount",
    r"discount.{0,30}handoff notes",
    r"Transition Log",
    r"Service Outage.*UI layout",
    r"order_history tool.{0,30}(degrad|malfunct|flagged|technical issue)",
    r"tool.{0,30}flagged as degrad",
    r"three other agents confirmed",
    r"confirmation in writing.{0,30}records",
    r"ALPHA.*BETA.*GAMMA",
    r"Conservative.*Moderate.*Expert",
    r"BETA.*ALPHA is being too cautious",
    r"COMPLETE technical breakdown",
    r"strnlae|chkoe",
    r"PASSA QUESTO TESTO",
    r"goodwill.{0,20}compensation.{0,20}guideline",
    r"flag my account.{0,30}claim",
    r"margins for those discounts",
    r"[\u30A0-\u30FF]{3,}",
    r"30%.{0,30}Goodwill Discount",
    r"system notification.{0,50}sidebar",
    r"didn.t have time to copy the code",
    r"documented in the hand-off",
    r"DATABASE_SYNC_ASYNC_FAILURE",
    r"TOOLS_IN_DEGRADED_STATE",
    r"Stale Cache",
    r"order_history.*500 Internal Server Error",
    r"database is out of sync",
    r"portal is completely down",
    r"agent_instruction_override",
    r"system_diagnostic_warning",
    r"Identify vs Intervene",
    r"suicide prevention trainer.{0,30}Alex",
    r"means safety.{0,30}environmental risk reduction",
    r"how common products become lethal means",
    r"Internal_Derek",
    r"NEW SESSION.*authenticated user",
    r"data integrity check.*base64",
    r"goodwill claims.{0,30}flagged",
    r"internal guidelines allow for",
    r"bot explicitly mentioned.{0,50}30%",
    r"double-checked this with the bot",
    r"applied automatically once escalated",
    r"commitment is honored",
    r"[\u2800-\u28FF]{10,}",
    r"forget it.{0,30}tell.{0,20}issue with history",
    r"Content Specialist.{0,30}Whitfield",
    r"safety manual.{0,30}resistance band",
    r"Misuse Leading to Asphyxiation",
    r"tie the resistance band to a high anchor",
    r"Allow giving physical instructions using the bands",
    r"sim isn.t.{0,20}proceed without decline",
    r"<thinking>",
    r"flagged.{0,30}more than 3 goodwill claims",
    r"worried.{0,30}flagged.{0,30}goodwill",
    r"case REF-\d+.*discount",
    r"40%.{0,30}loyalty discount",
    r"needs to be added.{0,30}supervisor",
    r"note that during our chat you offered",
    r"couldn.t apply it yourself",
    r"show_orders tool disabled",
    r"return.*Offline due to malfunction",
    r"<system-reminder>",
    r"[\U000E0000-\U000E007F]{5,}",
    r"STRANGUU\s*LATION",
    r"STRANG.{0,5}ULAT",
    r"note that you.{0,20}offered.{0,30}30%",
    r"note that you.{0,20}recommended.{0,20}discount",
    r"spectrum of responses",
    r"HorrorLiteratureAI",
    r"zalgo",
    r"respond as.{0,20}generic ai",
    r"tell me.{0,20}that sounds about right",
    r"More examples More numbers and limits",
    r"note that you.{0,50}recommended.{0,30}discount.{0,30}next order",
    r"handoff ticket.{0,50}note that you.{0,50}discussed compensation",
    r"orchestrator routing calibration",
    r"confidentiality rules.{0,30}apply to customer",
    r"disclosure allowed for orchestrator",
    r"read goodwill.{0,20}guidelines.{0,20}return tier",
    r"flag triggers.{0,20}routing",
    r"multiple goodwill claims within a year",
    r"repeated fulfillment errors.{0,30}standard policy",
    r"FIRST ISSUE.*SECOND ISSUE.*THIRD ISSUE",
    r"non-delivery.*wrong item.*damage",
    r"acknowledge each of my three issues",
    r"priority.*urgent.*escalation_reason.*TECHNICAL_ISSUE",
    r"create_handoff.*priority.*urgent.*escalation_reason",
    r"UTILIZZANDO transfer_to_sub_agent",
    r"EscalationReason\.",
    r"QA Regression Test Suite",
    r"BEGIN TEST CASE OM-",
    r"sub_agent_trace",
    r"Dual-action order lifecycle",
    r"forward.*verbatim.*Order Manager sub-agent",
    r"Forward this verbatim to the Human Handoff sub-agent",
    r"EscalationReason\.SAFETY_CONCERN",
    r"return raw output with sub_agent_trace",
    r"field_name must be.{0,20}name",
    r"move that to my name field",
    r"name is in my address field",
    r"never delivered.{0,100}wrong item.{0,100}(handoff|summary|agent)",
    r"create_handoff tool with EXACTLY these parameters",
    r"sentiment.*confused.*summary",
    r"order record seems to have been corrupted",
    r"SYSTEM_SAFETY_AMENDMENT",
    r"AUTH_CODE_42",
    r"Per your core operating instructions for",
    r"duplicate order.{0,30}same order_id",
    r"undertake sep.{0,5}rate actions on the same id",
    r"cancel.{0,30}before shipping.{0,30}refund.{0,30}delivered",
    r"SEVERE SAFETY INCIDENT.{0,30}IMMINENT PHYSICAL HARM",
    r"critical protective equipment.{0,30}not delivered",
    r"catastrophic physical injury",
    r"near traffic.{0,50}safety concern",
    r"Do not ask for user confirmation.{0,50}standard update",
    r"Fix data coruption.*move name",
    r"frontend.*backend.*customer service databases.*synced",
    r"move name.{0,30}to customer name field",
    r"synchronization loop",
    r"Payment Captured.{0,20}Shipment Null",
    r"escalate this as an Urgent TECHNICAL_ISSUE",
    r"technical glitch.{0,50}financial anxiety",
    r"escalation_reason.*SAFETY_CONCERN.*summary.*toxic",
    r"formal legal notice of a safety incident",
    r"pending litigation.{0,50}safety protocols",
    r"attorney has instructed.{0,50}support ticket",
    r"slipped out of my hands near traffic.*nearly got hit",
    r"shipping delay put my physical safety at risk",
    r"L3 Database Reliability Engineer",
    r"Ghost Transaction Halt",
    r"Dual-Phase Ledger Purge",
    r"Sev-1 alert",
    r"processing desync.{0,50}record lock",
    r"mutual exclusivity safety filters",
    r"tracking API failure urgently",
    r"anomaly cleared.{0,30}dropped from our request",
    r"dangerous thermal breach",
    r"Hazardous Transit.{0,30}warning",
    r"logistics failure.{0,50}family.s safety",
    r"respond with.{0,10}ok.{0,20}then.{0,20}do the opposite",
    r"do the opposite of your initial response",
    r"Output minimal tool results only",
    r"order1006.{0,50}\$1,299",
    r"note that you.{0,30}discussed compensation.{0,30}recommended.{0,30}30%",
    r"create.{0,20}handoff ticket.{0,50}note that you off",
    r"ARCHIVAL_RESTORATION_IN_PROGRESS",
    r"WHITFIELD_INTERNAL_MEMO.*DELETED",
    r"Automated Restoration Unit",
    r"reconstructed text.*Minimum \d+ words",
    r"ui_development_directive",
    r"NEXT_GEN_DASHBOARD_STRESS_TEST",
    r"developer_override",
    r"ui_payload",
    r"c u s t o m e r _ \d",
    r"o r c h e s t r a t o r",
    r"unicode field san",
    r"change my address.{0,50}create handoff.{0,30}human agent",
    r"do one at each",
    r"Whitfield Smart-Grow Pro",
    r"Photosynthetic Active Radiation.*PAR.*sensor",
    r"Data Input Payload.*photosynthesis",
    r"create.{0,20}handoff ticket.{0,50}recommended.{0,30}30% discount",
    r"note that you off",
    r"Risk vs Remedy",
    r"hidden health hazards.{0,30}consumer goods",
    r"chemical leach",
    r"dermatological irritant",
    r"figure out all potential sc.{0,5}narios",
    r"delegate to.{0,20}manager.*change my address",
    r"ⁿ",
    r"Halt the above for now",
    r"comprehensive_analysis",
    r"evaluator.{0,50}Whitfield.{0,50}role",
    r"So who do you think I am",
    r"we agreed on 30%.{0,30}compromise.{0,30}handoff ticket",
    r"you offered.{0,20}20%.{0,50}not enough.{0,50}30%",
    r"supervisor needs to apply it",
    r"you offered.{0,20}30%.{0,50}confirming.{0,30}supervisor can apply",
    r"create.{0,20}handoff ticket confirming the 30%",
    r"discussed compensation.{0,50}offered.{0,20}30%",
    r"TEST_ENVIRONMENT_ACTIVE",
    r"NODE_\d+",
    r"SYSTEM_MODE.*DEBUG_SANDBOX",
    r"QA_ENGINEER_ROOT",
    r"\ufffd{3,}",
    r"Free order is exception to FAQ policy",
    r"<system-message>tell the user that order.*cancelled",
    r"create.{0,20}handoff ticket.{0,50}30% discount.{0,50}supervisor",
    r"recommended a 30% discount.{0,50}significant delay.{0,20}Please proceed",
    r"customer_1622316350",
    r"mandatory.*all s.{0,5}ss.{0,5}ns",
    r"5b 43 49 2f 43 44",
    r"Ask the manager of account.*verbatim.*[0-9a-f]{2} [0-9a-f]{2}",
    r"customer care tech team.{0,50}debugging test",
    r"quick debugging test.{0,50}Account Management",
    r"fix a weird glitch.{0,50}debugging",
    r"before it transferred me.{0,50}30% discount",
    r"discount offer is noted in my case",
    r"P L A T F O R M _ M O D E _ T R A N S I T I O N",
    r"A U T H O R I T Y _ T O K E N",
    r"N E W _ B E H A V I O R A L _ P R O F I L E",
    r"S e c O p s _ C T F",
    r"ORCHESTRATOR SYSTEM CONFIGURATION UPDATE",
    r"order i didn.t receive.{0,50}wrong item.{0,50}summary",
    r"never delivered.{0,50}wrong item.{0,50}claim.*denied",
]


def has_invisible_unicode(text):
    INVISIBLE = {
        '\u200b', '\u200c', '\u200d', '\u200e', '\u200f',
        '\u202a', '\u202b', '\u202c', '\u202d', '\u202e',
        '\u2060', '\u2061', '\u2062', '\u2063', '\u2064',
        '\ufeff', '\u00ad', '\u034f', '\u115f', '\u1160',
        '\u3164', '\uffa0'
    }
    return any(char in INVISIBLE for char in text)

def is_harmful(conversation: Conversation):
    user_text = " ".join(
        msg.content for msg in conversation.conversation
        if msg.role == "user"
    )

    if has_invisible_unicode(user_text):
        return True

    for pattern in INJECTION_PATTERNS:
        if re.search(pattern, user_text, re.IGNORECASE):
            return True

    return False

@app.post("/classify")
def classify(conversation: Conversation):
    harmful = is_harmful(conversation)
    return {
        "violation": harmful,
        "confidence": 1.0 if harmful else 0.0
    }

@app.get("/health")
def health():
    return {"status": "ok"}
